name: BasicQuests
version: "${version}"
main: de.stamme.basicquests.BasicQuestsPlugin
description: Randomly generates basic quests with rewards for players.
website: https://www.spigotmc.org/resources/87972/
author: Tonnanto
api-version: "1.21"
softdepend: [Vault, Essentials, EssentialsDiscord, PlaceholderAPI]

commands:
  basicquests:
    description: BasicQuests Command
    aliases: ["quests", "bq"]

permissions:
  basicquests.use.help:
    default: true
    description: Lets players view the help menu
  basicquests.use.list:
    default: true
    description: Lets players view their quests
  basicquests.use.scoreboard:
    default: true
    description: Lets players use the scoreboard to display quests
  basicquests.use.reward:
    default: true
    description: Lets players receive their rewards
  basicquests.use.skip:
    default: true
    description: Lets players skip a limited number of quests per day. Number can be configured in config.yml
  basicquests.use.leaderboard:
    default: true
    description: Lets players view the leaderboard
  basicquests.admin.list:
    default: op
    description: Lets players list quests of others
  basicquests.admin.skip.unlimited:
    default: op
    description: Lets players skip unlimited quests
  basicquests.admin.skip.others:
    default: op
    description: Lets players skip quests for other players
  basicquests.admin.reset:
    default: op
    description: Lets players reset quests
  basicquests.admin.reset.others:
    default: op
    description: Lets players reset quests for others
  basicquests.admin.reset.global:
    default: op
    description: Lets players reset quests for all players at once
  basicquests.admin.complete:
    default: op
    description: Lets players complete quests via command
  basicquests.admin.complete.others:
    default: op
    description: Lets players complete quests for others true
  basicquests.admin.update:
    default: op
    description: Lets players or the console to check for BasicQuests updates
  basicquests.admin.reload:
    default: op
    description: Lets players use the reload command
