name: BasicQuests
version: 0.3.3
main: de.stamme.basicquests.Main
description: Randomly generates basic quests with rewards for players.

author: Tonnanto
api-version: "1.16"
softdepend: [Vault, Essentials, PlaceholderAPI]

commands:
  quests:
    description: Shows currently active quests.
    usage: /<command> [detail]
  getreward:
    description: Recieve rewards from your completed quests.
    usage: /<command>
  showquests:
    description: Shows quests in a separate view.
    usage: /<command>
  hidequests:
    description: Hides quests.
    usage: /<command>
  resetquests:
    description: Reset quests.
    usage: /<command> [player]
  skipquest:
    description: Lets you select a quest to skip.
    usage: /<command>
  completequest:
    description: Lets you select a quest to complete instantly.
    usage: /<command>


permissions:
  quests.*:
    default: op
    description: Give players with op every permission by default.

  quests.reset:
    default: op
    description: Allows a player to use /resetquests.
  quests.reset.forothers:
    default: op
    description: Allows a player to reset other players quests with /resetquests.
  quests.complete:
    default: op
    description: Allows a player to use /completequest.
  quests.complete.forothers:
    default: op
    description: Allows a player to complete other players quests with /completequest.
  quests.skip:
    default: op
    description: Allows a player to use /skipquest as often as he wants to.
  quests.skip.forothers:
    default: op
    description: Allows a player to skip other players quests with /skipquest.
  quests.update:
    default: op
    description: Allows a user or the console to check for BasicQuests updates
