package de.stamme.basicquests.model.rewards;

public enum ItemRewardType {
    ARMOR_REWARDS, ENCHANTMENT_REWARDS, FOOD_REWARDS, OTHER_ITEM_REWARDS, POTION_REWARDS, RESOURCE_REWARDS, TOOL_REWARDS, SMITHING_TEMPLATE_REWARDS
}
